/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_crypto_core_symmetric_AES */

#ifndef _Included_org_openhitls_crypto_core_symmetric_AES
#define _Included_org_openhitls_crypto_core_symmetric_AES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhitls_crypto_core_symmetric_AES
 * Method:    nativeInit
 * Signature: (I[B[BII)J
 */
JNIEXPORT jlong JNICALL Java_org_openhitls_crypto_core_symmetric_AES_nativeInit
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     org_openhitls_crypto_core_symmetric_AES
 * Method:    nativeUpdate
 * Signature: (J[BII[BI)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_core_symmetric_AES_nativeUpdate
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     org_openhitls_crypto_core_symmetric_AES
 * Method:    nativeFinal
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_core_symmetric_AES_nativeFinal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_crypto_core_symmetric_AES
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_core_symmetric_AES_nativeFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
