/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_crypto_ECDSA */

#ifndef _Included_org_openhitls_crypto_ECDSA
#define _Included_org_openhitls_crypto_ECDSA
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_openhitls_crypto_ECDSA
 * Method:    generateKeyPair
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_ECDSA_generateKeyPair
  (JNIEnv *, jobject);

/*
 * Class:     org_openhitls_crypto_ECDSA
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_ECDSA_encrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_openhitls_crypto_ECDSA
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_ECDSA_decrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_openhitls_crypto_ECDSA
 * Method:    sign
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_ECDSA_sign
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_openhitls_crypto_ECDSA
 * Method:    verify
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openhitls_crypto_ECDSA_verify
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif 