/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_crypto_core_mac_HMAC */

#ifndef _Included_org_openhitls_crypto_core_mac_HMAC
#define _Included_org_openhitls_crypto_core_mac_HMAC
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_openhitls_crypto_core_mac_HMAC
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_org_openhitls_crypto_core_mac_HMAC_nativeInit
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     org_openhitls_crypto_core_mac_HMAC
 * Method:    nativeUpdate
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_core_mac_HMAC_nativeUpdate
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_openhitls_crypto_core_mac_HMAC
 * Method:    nativeDoFinal
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_core_mac_HMAC_nativeDoFinal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_crypto_core_mac_HMAC
 * Method:    nativeReinit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_core_mac_HMAC_nativeReinit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_crypto_core_mac_HMAC
 * Method:    nativeGetMacLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openhitls_crypto_core_mac_HMAC_nativeGetMacLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_crypto_core_mac_HMAC
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_core_mac_HMAC_nativeFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif