/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_crypto_SM3 */

#ifndef _Included_org_openhitls_crypto_SM3
#define _Included_org_openhitls_crypto_SM3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhitls_crypto_SM3
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_SM3_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_openhitls_crypto_SM3
 * Method:    nativeUpdate
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_SM3_nativeUpdate
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     org_openhitls_crypto_SM3
 * Method:    nativeDoFinal
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_SM3_nativeDoFinal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
