/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_crypto_SM4 */

#ifndef _Included_org_openhitls_crypto_SM4
#define _Included_org_openhitls_crypto_SM4
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_openhitls_crypto_SM4
 * Method:    nativeInit
 * Signature: (I[B[BI)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_SM4_nativeInit
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     org_openhitls_crypto_SM4
 * Method:    nativeSetPadding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_SM4_nativeSetPadding
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openhitls_crypto_SM4
 * Method:    nativeEncryptUpdate
 * Signature: ([BII[BI[I)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_SM4_nativeEncryptUpdate
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jintArray);

/*
 * Class:     org_openhitls_crypto_SM4
 * Method:    nativeDecryptUpdate
 * Signature: ([BII[BI[I)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_SM4_nativeDecryptUpdate
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jintArray);

/*
 * Class:     org_openhitls_crypto_SM4
 * Method:    nativeEncryptFinal
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_SM4_nativeEncryptFinal
  (JNIEnv *, jobject);

/*
 * Class:     org_openhitls_crypto_SM4
 * Method:    nativeDecryptFinal
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_SM4_nativeDecryptFinal
  (JNIEnv *, jobject);

/*
 * Class:     org_openhitls_crypto_SM4
 * Method:    nativeReinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_SM4_nativeReinit
  (JNIEnv *, jobject);

/*
 * Class:     org_openhitls_crypto_SM4
 * Method:    nativeGetBlockSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openhitls_crypto_SM4_nativeGetBlockSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif