/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_crypto_core_hash_MessageDigest */

#ifndef _Included_org_openhitls_crypto_core_hash_MessageDigest
#define _Included_org_openhitls_crypto_core_hash_MessageDigest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhitls_crypto_core_hash_MessageDigest
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_core_hash_MessageDigest_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openhitls_crypto_core_hash_MessageDigest
 * Method:    nativeUpdate
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_core_hash_MessageDigest_nativeUpdate
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_openhitls_crypto_core_hash_MessageDigest
 * Method:    nativeDoFinal
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhitls_crypto_core_hash_MessageDigest_nativeDoFinal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_openhitls_crypto_core_hash_MessageDigest
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_core_hash_MessageDigest_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhitls_crypto_core_hash_MessageDigest
 * Method:    getContextPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openhitls_crypto_core_hash_MessageDigest_getContextPtr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
