# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  OPENHITLS_DIR: platform/openhitls
  SECURE_C_DIR: platform/openhitls/platform/Secure_C
  LIB_OUTPUT_DIR: ${{ github.workspace }}/libs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Create libs directory
      run: mkdir -p ${{ env.LIB_OUTPUT_DIR }}/libs/build

    - name: Download OpenHiTLS
      run: |
        mkdir -p ${{ github.workspace }}/platform
        cd ${{ github.workspace }}/platform
        git clone --recurse-submodules https://gitcode.com/openhitls/openhitls.git
  
    - name: Build Secure_C
      run: |
        cd ${{ github.workspace }}/${{ env.SECURE_C_DIR }}
        make -j$(nproc)
        cp lib/libboundscheck.a ${{ env.LIB_OUTPUT_DIR }}/build
  
    - name: Build OpenHiTLS
      run: |
        mkdir -p ${{ github.workspace }}/${{ env.OPENHITLS_DIR }}/build
        cd ${{ github.workspace }}/${{ env.OPENHITLS_DIR }}/build
        python3 ../configure.py --enable \
            hitls_bsl hitls_crypto hitls_tls hitls_pki hitls_auth \
            --lib_type static \
            --add_options="-DHITLS_EAL_INIT_OPTS=9 -DHITLS_CRYPTO_ASM_CHECK" \
            --add_link_flags="-L${{ github.workspace }}/${{ env.SECURE_C_DIR }}/lib -ldl" \
            --bits=64 --system=linux
        cmake ..
        make -j$(nproc)
        # Copy all OpenHiTLS .so files to the libs directory
        find . -name "*.a" -type f -exec cp {} ${{ env.LIB_OUTPUT_DIR }}/ \;
        cp -rf ../include ${{ env.LIB_OUTPUT_DIR }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
